# 노드 14 이미지 사용
FROM node:14 as build

# 앱 디렉토리 생성
WORKDIR /app

# 앱 종속성 설치
COPY package*.json ./
RUN yarn

# 앱 소스 추가
COPY . .

# 앱 빌드
RUN yarn build

# Nginx 이미지 사용
FROM nginx

# Nginx 설정 파일 복사
COPY nginx.conf /etc/nginx/nginx.conf

# 빌드된 앱 파일 복사
COPY --from=build /app /usr/share/nginx/html

# 외부로 노출할 포트 설정
EXPOSE 5173

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]